### ISSUE TITLE
Can we have release tags that match ocp releases?

### ISSUE THREAD

**Issue by martinkennelly** [openshift/runbooks#113]
Hey,
I want to link to versionable runbooks - an easy way would be to refer to a tag here. I dont want to pin to a commit as it makes it hard to read what version we are pulling.

I propose adding a tag for each OCP release.

**Comment by simonpasquier** [comment]
I remember that we had this discussion when we started the repository and the consensus was that it wasn't worth the overhead and it was ok to link to the `master` branch. It was assumed that a runbook would cover multiple OCP versions and having a single branch means that any refinement to a runbook benefits to all OCP versions. We also have e2e testing checking that the `runbook_url` annotations link to an actual web page.

Having said that we can revise the decision though I'm not sure who would be empowered to cut tags.
cc @jan--f

**Comment by martinkennelly** [comment]
/close
Looks like for now, we wont have tags. We gotta think about the release when making changes to runbooks. /cc @bpickard22
