### ISSUE TITLE
Invalid promql query for investigating etcdHighNumberOfFailedGRPCRequests

### ISSUE THREAD

**Issue by faxm0dem** [openshift/runbooks#59]
The [promql for investigating etcdHighNumberOfFailedGRPCRequests](https://github.com/openshift/runbooks/blob/master/alerts/cluster-etcd-operator/etcdHighNumberOfFailedGRPCRequests.md) doesn't parse correctly:

![image](https://user-images.githubusercontent.com/112638/178437626-de0daf29-4c76-4a0f-890e-3a737710ebed.png)

The old query works though (the one before 196227b13d7f92b00ec4ef7a5208a53e2116ad5a)

**Comment by tjungblu** [comment]
Thanks Simon, let me take a look. I think we have to update another runbook entry as well.

**Comment by tjungblu** [comment]
fix in #60 not sure how that got screwed up on copy&paste...

**Comment by simonpasquier** [comment]
/close
#60 merged
